---
kind: "ConfigMap"
apiVersion: "v1"
data: {}
binaryData: {}
metadata:
  uid: "2740719f-10de-11ea-a2c1-06378c91f7d7"
  annotations: {}
  name: "nirmata-test"
  labels:
    nirmata.io/environment.type: "system"

---
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  uid: "08d38e14-2306-11ea-a2c1-06378c91f7d7"
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: "busybox"
  labels:
    nirmata.io/deployment.name: "busybox"
    nirmata.io/environment.type: "system"
    nirmata.io/component: "busybox"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      nirmata.io/component: "busybox"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      name: "busybox"
      labels:
        nirmata.io/deployment.name: "busybox"
        nirmata.io/environment.type: "system"
        nirmata.io/application.name: "test1"
        nirmata.io/component: "busybox"
    spec:
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 36
      nodeSelector: {}
      schedulerName: "default-scheduler"
      dnsPolicy: "ClusterFirst"
      containers:
      - name: "busybox"
        image: "busybox"
        command:
        - "sleep"
        - "3600"
        args: []
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: "50m"
            memory: "128Mi"
          requests: {}
      securityContext:
        supplementalGroups: []
